/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package handwritten.digit.recog.mnsit;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;

import javax.swing.JLabel;

/**
 *
 * @author mortimer
 */
public class HumannVsAiMnist extends javax.swing.JFrame {

    /**
     * Creates new form HumannVsAiMnist
     */
    int speed;
    boolean autoScroll;
    JLabel[][]pixel;
    NeuralNetwork net;
    public HumannVsAiMnist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        compGuess = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        computerScoreTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalViewedTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accuracyOverallTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        correctAnswerTxt = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        correctSoFarTxt = new javax.swing.JTextField();
        yayOrNayLbl = new javax.swing.JLabel();
        outConfTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        allOutTxt = new javax.swing.JTextField();
        numsLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        jLabel1.setText("Computer Guess");

        compGuess.setEditable(false);

        nextBtn.setText("Next Image");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Total computer got correct");

        computerScoreTxt.setEditable(false);
        computerScoreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerScoreTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Images Viewed");

        totalViewedTxt.setEditable(false);
        totalViewedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalViewedTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Overall Accuracy Of Network (tested across whole data set) (%)");

        accuracyOverallTxt.setEditable(false);

        jLabel6.setText("Correct Answer");

        correctAnswerTxt.setEditable(false);

        exitBtn.setText("Menu");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Correct so far (%)");

        correctSoFarTxt.setEditable(false);

        outConfTxt.setEditable(false);

        jLabel17.setText("Confidence in answer(%) - higher percent = more confident");

        allOutTxt.setEditable(false);

        jLabel7.setText("Confidence (%) that image is number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(compGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(correctAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(nextBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(yayOrNayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalViewedTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(computerScoreTxt))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(accuracyOverallTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(correctSoFarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49))))
                        .addGap(161, 161, 161))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accuracyOverallTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerScoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalViewedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(correctSoFarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitBtn)
                            .addComponent(yayOrNayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(numsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn)
                    .addComponent(correctAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computerScoreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerScoreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerScoreTxtActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        this.nextBtn.setEnabled(true);
        this.setImage(this.pixel);

        
        
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void totalViewedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalViewedTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalViewedTxtActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        MenuUI men = new MenuUI();
        men.init(net);
        men.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyReleased

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1KeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
     // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */

    public void begin(NeuralNetwork net,boolean auto){
        this.autoScroll=auto;
        String ad="";
        String space="         ";
        for(int n =0;n<10;n++){
            ad=ad+String.valueOf(n)+space;
        }
        numsLbl.setText(ad);
        this.speed=0;
        this.net=net;
        this.autoScroll=false;
        int width=10;
        int noOfTrainingExamples=10000;//so that +1 lines
        int height=10;
        this.getRootPane().setDefaultButton(nextBtn);
        JLabel pixel [][]=new JLabel[28][28];
        for(int y=0;y<28;y++){
            for(int x =0;x<28;x++){
                pixel[y][x]=new JLabel();
                pixel[y][x].setText("");
                pixel[y][x].setSize(width, height);
                
                /*int white=Color.white.getRGB();
                int black = Color.black.getRGB();
                int difI = white-black;
                double dif = Double.parseDouble(String.valueOf(difI));
                int valueOfPixA=1;
                double valOfPix=Double.parseDouble(String.valueOf(valueOfPixA));
                double val =  (valOfPix*(dif/255.0))+black;
                System.out.println("black "+black+" white "+white+" val "+val);*/
                pixel[y][x].setBackground(Color.red);
                this.jPanel1.add(pixel[y][x]);
                pixel[y][x].setLocation(x*width+width, y*height+height);
                pixel[y][x].setVisible(true);
                pixel[y][x].setOpaque(true);
            }
        }
        yayOrNayLbl.setVisible(true);
        yayOrNayLbl.setOpaque(true);
        double[] acc=this.net.testAccuracy();
        if(acc[0]==(9874.0/10000.0)*100.0){
            accuracyOverallTxt.setText("98.74");
        }else{
            accuracyOverallTxt.setText(String.valueOf(acc[0]));
        }
        totalViewedTxt.setText("0");
        computerScoreTxt.setText("0");
        this.pixel=pixel;
        this.setImage(this.pixel);
        while(auto){
            this.setImage(this.pixel);
            this.update(this.getGraphics());

        }

    }
    public  void setImage(JLabel[][]pixel){
        
            double[]line =getImageAndAnswer();
            double correctAnswer=line[0];
            correctAnswerTxt.setText(String.valueOf(correctAnswer));
            double[]in = new double[784];
            for(int i =0;i<784;i++){
                in[i]=line[i+1]/255.0;
            }
            double[]out = this.net.feedThroughNet(in);
            double ans[]={0,1,2,3,4,5,6,7,8,9};
            double computerAnswer = NeuralNetwork.getAnswerGivenArray(out);
            String all="";
            for(int i =0;i<ans.length;i++){
                String one="";
                for(int cha=0;cha<String.valueOf(out[i]*100.0).length()&&cha<5;cha++){
                    one = one+String.valueOf(out[i]*100.0).charAt(cha);
                }
                all=all+one+"  ";
                if(ans[i]==computerAnswer){
                   outConfTxt.setText(String.valueOf(out[i]*100.0));
                }
            }
            allOutTxt.setText(all);
            compGuess.setText(String.valueOf(computerAnswer));
            if(computerAnswer==correctAnswer){
                computerScoreTxt.setText(String.valueOf(Integer.parseInt(computerScoreTxt.getText())+1));
                yayOrNayLbl.setBackground(Color.green);
            }else{
                yayOrNayLbl.setBackground(Color.red);
            }

            int index=0;
            for(int y=0;y<28;y++){
                for(int x=0;x<28;x++){
                    int white=Color.white.getRGB();
                    int black = Color.black.getRGB();
                    int difI = white-black;
                    double dif = Double.parseDouble(String.valueOf(difI));
                    double valOfPix=in[index]*255.0;
                    index++;
                    double val =  (valOfPix*(dif/255.0))+black;
                    int valNew=(int)Math.round(val);
                    Color r = new Color(valNew);
                    this.pixel[y][x].setBackground(r);
                }
            }
        totalViewedTxt.setText(String.valueOf(Integer.parseInt(totalViewedTxt.getText())+1));
        double co=Double.parseDouble(computerScoreTxt.getText())/Double.parseDouble(totalViewedTxt.getText());
        co=co*100.0;
        String c="";
        for(int ch=0;ch<String.valueOf(co).length()&&ch<5;ch++){
            c=c+String.valueOf(co).charAt(ch);
        }
        correctSoFarTxt.setText(c);
    }
    public double[] getImageAndAnswer(){
        //returns array 0 th element is answer rest are pxiel values from 0 to 255
        Random r = new Random();
        int lineChoosen=r.nextInt(10001)+1;//retruns anything from 1 to 10,001 
        int lineNo=-1;
        String lineString;
        String[]lineS;
        double[]out= new double[1];
        try{
            FileReader reader = new FileReader(this.net.getTestFileName());
            BufferedReader buff = new BufferedReader(reader);
            while((lineString=buff.readLine())!=null){
                lineNo++;
                if(lineNo==lineChoosen){
                    lineS=lineString.split(",");
                    out = new double[lineS.length];
                    for(int i =0;i<lineS.length;i++){
                        out[i]=Double.parseDouble(lineS[i]);
                    }
                }else if(lineNo>lineChoosen){
                    break;
                }
            }
        }catch(IOException e){
            System.out.println("Error "+e+" with file "+this.net.getTestFileName());
            e.printStackTrace();
        }
        return out;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumannVsAiMnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumannVsAiMnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumannVsAiMnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumannVsAiMnist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumannVsAiMnist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accuracyOverallTxt;
    private javax.swing.JTextField allOutTxt;
    private javax.swing.JTextField compGuess;
    private javax.swing.JTextField computerScoreTxt;
    private javax.swing.JTextField correctAnswerTxt;
    private javax.swing.JTextField correctSoFarTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel numsLbl;
    private javax.swing.JTextField outConfTxt;
    private javax.swing.JTextField totalViewedTxt;
    private javax.swing.JLabel yayOrNayLbl;
    // End of variables declaration//GEN-END:variables
}
